version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chat_network

  setup:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - chat_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=chat_project.settings

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - setup
    networks:
      - chat_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=chat_project.settings

  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start_daphne.sh
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    depends_on:
      - redis
      - django
    networks:
      - chat_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=chat_project.settings

volumes:
  redis_data:

networks:
  chat_network:
    driver: bridge 