# Generated by Django 4.2.20 on 2025-04-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_sample_data'),
        ('chat', '0004_alter_message_options_remove_message_timestamp_and_more'),
    ]

    operations = [
    ]
